---
services:
  app:
    image: pi2me/domainmod-frankenphp
    container_name: domainmod_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DOMAINMOD_DATABASE_HOST=db
      - DOMAINMOD_DATABASE=domainmod
      - DOMAINMOD_DB_USER=domainmod
      - DOMAINMOD_DB_PASSWORD=1f74cc83
      - SERVER_NAME=http://localhost:8080
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
      - app_data:/app
    ports:
      - 8080:8080
    restart: unless-stopped

  db:
    image: ghcr.io/linuxserver/mariadb:latest
    container_name: domainmod_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - MYSQL_DATABASE=domainmod
      - MYSQL_USER=domainmod
      - MYSQL_PASSWORD=1f74cc83
      - MYSQL_ROOT_PASSWORD=e2d1c034
    volumes:
      - ./database:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", '-p$$MYSQL_ROOT_PASSWORD']
      start_period: 8s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:    
  app_data: